-- MySQL Script generated by MySQL Workbench
-- len 07 out 2023 17:11:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema Bibliyotek
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Bibliyotek` DEFAULT CHARACTER SET 'utf8' ;
USE `Bibliyotek` ;

-- -----------------------------------------------------
-- Table `Bibliyotek`.`Liv`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bibliyotek`.`Liv` (
  `idLiv` INT NOT NULL,
  `tit` VARCHAR(45) NULL,
  `ote` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idLiv`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


