-- MySQL Script generated by MySQL Workbench
-- len 07 out 2023 17:56:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema Boutik
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Boutik` ;
USE `Boutik` ;

-- -----------------------------------------------------
-- Table `Boutik`.`Pwodwi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Boutik`.`Pwodwi` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Boutik`.`Kategori`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Boutik`.`Kategori` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Boutik`.`Kliyan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Boutik`.`Kliyan` (
)
ENGINE = InnoDB;



